import { NextRequest, NextResponse } from "next/server";
import { buildCopilotSuggestion } from "@/lib/copilot";
import { callLlm } from "@/lib/ai/llm";

// NOTE: Copilot suggestions do NOT burn generation credits — they are purely
// a routing helper. The 401 / auth gate is only triggered by downstream
// /api/generate calls. This route is intentionally open to anonymous users
// with unlimited queries.
//
// Architecture: action chips come from the deterministic rule engine
// (buildCopilotSuggestion) so deep-links stay reliable and testable. The
// reply TEXT is generated by a real LLM via fal-ai/any-llm when FAL_KEY is
// configured — falling back to the rule-engine's canned reply on timeout or
// error so the UX never breaks.

interface Message {
  role: "user" | "assistant";
  content: string;
}

export async function POST(req: NextRequest) {
  let body: { messages?: unknown; intent?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid" }, { status: 400 });
  }

  // Validate messages
  if (!Array.isArray(body.messages) || body.messages.length === 0) {
    return NextResponse.json({ error: "invalid" }, { status: 400 });
  }

  if (body.messages.length > 50) {
    return NextResponse.json({ error: "invalid" }, { status: 400 });
  }

  const messages = body.messages as Message[];

  // Validate each message
  for (const msg of messages) {
    if (
      typeof msg !== "object" ||
      msg === null ||
      !["user", "assistant"].includes(msg.role) ||
      typeof msg.content !== "string"
    ) {
      return NextResponse.json({ error: "invalid" }, { status: 400 });
    }
  }

  // Optional intent tag from starter grid
  const intent =
    typeof body.intent === "string" && body.intent.length > 0
      ? body.intent
      : undefined;

  // Get the last user message
  const lastUserMessage =
    [...messages].reverse().find((m) => m.role === "user")?.content ?? "";

  if (!lastUserMessage) {
    return NextResponse.json({ error: "invalid" }, { status: 400 });
  }

  // Deterministic action chips — always reliable.
  const suggestion = buildCopilotSuggestion(lastUserMessage, intent);

  // Real LLM reply — swaps in a natural response when FAL_KEY is available.
  // On timeout / error, we keep the rule-engine's reply so the UX never breaks.
  const llmReply = await callLlm(messages, { timeoutMs: 15000 });

  return NextResponse.json({
    ...suggestion,
    reply: llmReply ?? suggestion.reply,
  });
}
