import type { ToolDef } from "./p2-tools";

export const P3_TOOLS: ToolDef[] = [
  {
    id: "edit-image",
    slug: "edit-image",
    name: "Edit Image",
    description: "Image edit workspace with inpaint model.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "image", label: "Image", type: "image" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "edit-video",
    slug: "edit-video",
    name: "Edit Video",
    description: "Video edit workspace.",
    category: "editing",
    mediaOut: "video",
    inputs: [
      { key: "video", label: "Video URL", type: "text" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "draw-to-edit",
    slug: "draw-to-edit",
    name: "Draw to Edit",
    description: "Mask-draw image inpaint.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "image", label: "Image", type: "image" },
      { key: "mask", label: "Mask", type: "image" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "draw-to-video",
    slug: "draw-to-video",
    name: "Draw to Video",
    description: "Mask-draw video inpaint.",
    category: "editing",
    mediaOut: "video",
    inputs: [
      { key: "video", label: "Video URL", type: "text" },
      { key: "mask", label: "Mask", type: "image" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "upscale",
    slug: "upscale",
    name: "Upscale",
    description: "Topaz-style image upscaler.",
    category: "editing",
    mediaOut: "image",
    inputs: [{ key: "image", label: "Image", type: "image" }],
  },
  {
    id: "image-bg-remover",
    slug: "image-bg-remover",
    name: "Image Background Remover",
    description: "Remove background from image.",
    category: "editing",
    mediaOut: "image",
    inputs: [{ key: "image", label: "Image", type: "image" }],
  },
  {
    id: "video-bg-remover",
    slug: "video-bg-remover",
    name: "Video Background Remover",
    description: "Remove background from video.",
    category: "editing",
    mediaOut: "video",
    inputs: [{ key: "video", label: "Video URL", type: "text" }],
  },
  {
    id: "color-grading",
    slug: "color-grading",
    name: "Color Grading",
    description: "Color grade videos and images.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "image", label: "Image", type: "image" },
      { key: "prompt", label: "Look / mood", type: "prompt" },
    ],
  },
  {
    id: "inpaint",
    slug: "inpaint",
    name: "Inpaint",
    description: "Region inpaint editor.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "image", label: "Image", type: "image" },
      { key: "mask", label: "Mask", type: "image" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "lipsync-studio",
    slug: "lipsync-studio",
    name: "Lipsync Studio",
    description: "Lipsync audio to video avatar.",
    category: "editing",
    mediaOut: "video",
    inputs: [
      { key: "image", label: "Face image", type: "image" },
      { key: "audio", label: "Audio URL", type: "text" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "talking-avatar",
    slug: "talking-avatar",
    name: "Talking Avatar",
    description: "Talking head avatar generator.",
    category: "editing",
    mediaOut: "video",
    inputs: [
      { key: "image", label: "Face image", type: "image" },
      { key: "audio", label: "Audio URL", type: "text" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "kling-avatars-2",
    slug: "kling-avatars-2",
    name: "Kling Avatars 2.0",
    description: "Kling-based avatar system.",
    category: "editing",
    mediaOut: "video",
    inputs: [
      { key: "image", label: "Face image", type: "image" },
      { key: "audio", label: "Audio URL", type: "text" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "motion-control",
    slug: "motion-control",
    name: "Motion Control",
    description: "30s character motion control with Kling 3.",
    category: "editing",
    mediaOut: "video",
    inputs: [
      { key: "image", label: "Character image", type: "image" },
      { key: "prompt", label: "Motion prompt", type: "prompt" },
    ],
  },
  {
    id: "multi-reference",
    slug: "multi-reference",
    name: "Multi Reference",
    description: "Multi-image reference editing.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "ref1", label: "Reference 1", type: "image" },
      { key: "ref2", label: "Reference 2", type: "image" },
      { key: "ref3", label: "Reference 3", type: "image" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "banana-placement",
    slug: "banana-placement",
    name: "Banana Placement",
    description: "Object placement via Nano Banana.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "scene", label: "Scene", type: "image" },
      { key: "object", label: "Object", type: "image" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "product-placement",
    slug: "product-placement",
    name: "Product Placement",
    description: "Canvas-based product placement.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "scene", label: "Scene", type: "image" },
      { key: "product", label: "Product", type: "image" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "clipcut",
    slug: "clipcut",
    name: "ClipCut",
    description: "Auto clip-cutting tool.",
    category: "editing",
    mediaOut: "video",
    inputs: [
      { key: "video", label: "Video URL", type: "text" },
      { key: "prompt", label: "Instructions", type: "prompt" },
    ],
  },
  {
    id: "transitions",
    slug: "transitions",
    name: "Transitions",
    description: "Transition effects between clips.",
    category: "editing",
    mediaOut: "video",
    inputs: [
      { key: "clipA", label: "Clip A URL", type: "text" },
      { key: "clipB", label: "Clip B URL", type: "text" },
      { key: "prompt", label: "Transition style", type: "prompt" },
    ],
  },
  {
    id: "expand-image",
    slug: "expand-image",
    name: "Expand Image",
    description: "Outpaint / canvas expand.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "image", label: "Image", type: "image" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "skin-enhancer",
    slug: "skin-enhancer",
    name: "Skin Enhancer",
    description: "Skin retouch enhancement.",
    category: "editing",
    mediaOut: "image",
    inputs: [{ key: "image", label: "Image", type: "image" }],
  },
  {
    id: "relight",
    slug: "relight",
    name: "Relight",
    description: "Relight subjects in an image.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "image", label: "Image", type: "image" },
      { key: "prompt", label: "Lighting prompt", type: "prompt" },
    ],
  },
  {
    id: "recast",
    slug: "recast",
    name: "Recast",
    description: "Recast scene content.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "image", label: "Image", type: "image" },
      { key: "prompt", label: "Prompt", type: "prompt" },
    ],
  },
  {
    id: "angles-2",
    slug: "angles-2",
    name: "Angles 2.0",
    description: "Change camera angle of a subject.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "image", label: "Image", type: "image" },
      { key: "prompt", label: "Angle prompt", type: "prompt" },
    ],
  },
  {
    id: "shots",
    slug: "shots",
    name: "Shots",
    description: "Cinematic shot variations.",
    category: "editing",
    mediaOut: "image",
    inputs: [
      { key: "image", label: "Image", type: "image" },
      { key: "prompt", label: "Shot prompt", type: "prompt" },
    ],
  },
];
